version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      
  api:
    build: ./services/api
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/trekktribe
      - NODE_ENV=development
      - PORT=4000
      - JWT_SECRET=devsecret123456789
    ports:
      - '4000:4000'
    depends_on:
      - mongo
      
  web:
    build: ./web
    restart: unless-stopped
    ports:
      - '3000:80'
    depends_on:
      - api
      
volumes:
  mongo_data:

