services:
  - type: web
    name: trekk-tribe-api
    env: node
    region: oregon
    plan: free
    rootDir: services/api
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      # Add these variables manually in Render dashboard:
      # MONGODB_URI, JWT_SECRET, SESSION_SECRET, FRONTEND_URL
